Repository kubernetes-sigs/dra-example-driver, pull requests merged in 2023-04, with the labels that each got.

#5 Address feedback from early users of the repo
  README.md
  demo/demo-apps.png
  demo/gpu-test1.yaml
  demo/gpu-test2.yaml
  demo/gpu-test3.yaml
  demo/gpu-test4.yaml
Labels: lgtm, size/M, approved, cncf-cla: yes

#6 Rename ClaimRequests->AllocatedClaims & ClaimAllocations->PreparedClaims
  README.md
  api/example.com/resource/gpu/nas/v1alpha1/nas.go
  api/example.com/resource/gpu/nas/v1alpha1/zz_generated.deepcopy.go
  cmd/dra-example-controller/allocations.go
  cmd/dra-example-controller/driver.go
  cmd/dra-example-controller/gpu.go
  cmd/dra-example-controller/requests.go
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/state.go
  deployments/helm/dra-example-driver/crds/nas.gpu.resource.example.com_nodeallocationstates.yaml
Labels: size/XL, lgtm, approved, cncf-cla: yes

#8 Fix CRD after renaming
  deployments/helm/dra-example-driver/crds/nas.gpu.resource.example.com_nodeallocationstates.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#7 Update to K8s 1.27
  common.mk
  demo/scripts/common.sh
  go.mod
  go.sum
Labels: lgtm, size/M, approved, cncf-cla: yes
