Repository kubernetes-sigs/dra-example-driver, pull requests merged in 2023-08, with the labels that each got.

#26 rename module to match k8s-sigs convention
  .gitignore
  README.md
  api/example.com/resource/gpu/nas/v1alpha1/client/client.go
  api/example.com/resource/gpu/v1alpha1/api.go
  cmd/dra-example-controller/allocations.go
  cmd/dra-example-controller/driver.go
  cmd/dra-example-controller/gpu.go
  cmd/dra-example-controller/main.go
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  cmd/dra-example-kubeletplugin/state.go
  cmd/set-nas-status/main.go
  common.mk
  go.mod
  go.sum
  pkg/example.com/resource/clientset/versioned/clientset.go
  pkg/example.com/resource/clientset/versioned/fake/clientset_generated.go
  pkg/example.com/resource/clientset/versioned/fake/register.go
  pkg/example.com/resource/clientset/versioned/scheme/register.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/deviceclassparameters.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/fake_deviceclassparameters.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/fake_gpu_client.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/fake_gpuclaimparameters.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/gpu_client.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/gpuclaimparameters.go
  pkg/example.com/resource/clientset/versioned/typed/nas/v1alpha1/fake/fake_nas_client.go
  pkg/example.com/resource/clientset/versioned/typed/nas/v1alpha1/fake/fake_nodeallocationstate.go
  pkg/example.com/resource/clientset/versioned/typed/nas/v1alpha1/nas_client.go
  pkg/example.com/resource/clientset/versioned/typed/nas/v1alpha1/nodeallocationstate.go
Labels: lgtm, size/L, approved, cncf-cla: yes

#19 CLI unification
  cmd/dra-example-controller/driver.go
  cmd/dra-example-controller/main.go
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  cmd/dra-example-kubeletplugin/state.go
  cmd/set-nas-status/main.go
  deployments/helm/dra-example-driver/templates/controller.yaml
  deployments/helm/dra-example-driver/templates/kubeletplugin.yaml
  go.mod
  go.sum
  pkg/flags/kubeclient.go
  pkg/flags/logging.go
  pkg/flags/nodeallocationstate.go
Labels: lgtm, size/XXL, approved, cncf-cla: yes

#27 pass ctx objects from cmd Run func down to the kubeClients
  .golangci.yaml
  api/example.com/resource/gpu/nas/v1alpha1/client/client.go
  cmd/dra-example-controller/driver.go
  cmd/dra-example-controller/main.go
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  cmd/set-nas-status/main.go
Labels: lgtm, size/L, approved, cncf-cla: yes

#28 [golangci-lint][goimports] add local imports check
  .golangci.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes

#24 Controller batch calls support
  cmd/dra-example-controller/driver.go
  go.mod
  go.sum
Labels: size/XL, lgtm, approved, cncf-cla: yes

#29 make .gitignore only ignore binaries
  .gitignore
Labels: lgtm, approved, size/XS, cncf-cla: yes

#25 Kubelet plugin switch to v1alpha3 api
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/state.go
Labels: lgtm, size/M, approved, cncf-cla: yes
