Repository kubernetes-sigs/dra-example-driver, pull requests merged in 2024-09, with the labels that each got.

#56 E2E Test
  .github/workflows/e2e.yaml
  Makefile
  test/e2e/e2e.sh
  test/e2e/setup-e2e.sh
  test/e2e/teardown-e2e.sh
Labels: lgtm, size/L, approved, cncf-cla: yes

#60 fix flakes for kind
  .github/workflows/e2e.yaml
  demo/scripts/create-kind-cluster.sh
  test/e2e/e2e.sh
Labels: lgtm, approved, size/XS, cncf-cla: yes

#58 Refactor how opaque device configs are handled
  .github/workflows/e2e.yaml
  .github/workflows/tests.yaml
  README.md
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/discovery.go
  cmd/dra-example-kubeletplugin/state.go
  common.mk
  go.mod
Labels: lgtm, size/L, approved, cncf-cla: yes

#61 demos: handle SIGTERM to avoid long termination
  demo/gpu-test1.yaml
  demo/gpu-test2.yaml
  demo/gpu-test3.yaml
  demo/gpu-test4.yaml
  demo/gpu-test5.yaml
  test/e2e/e2e.sh
Labels: lgtm, size/M, approved, cncf-cla: yes

#63 e2e: fail on errors
  test/e2e/e2e.sh
Labels: lgtm, approved, size/XS, cncf-cla: yes
