Repository kubernetes-sigs/dra-example-driver, pull requests merged in 2024-08, with the labels that each got.

#50 Update to work with Kubernetes 1.31
  .gitignore
  Makefile
  README.md
  cmd/dra-example-controller/claimparametersgen.go
  cmd/dra-example-controller/main.go
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/checkpoint.go
  cmd/dra-example-kubeletplugin/discovery.go
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  cmd/dra-example-kubeletplugin/state.go
  demo/gpu-test1.yaml
  demo/gpu-test2.yaml
  demo/gpu-test3.yaml
  demo/gpu-test4.yaml
  demo/scripts/build-kind-image.sh
  demo/scripts/common.sh
  demo/scripts/kind-cluster-config.yaml
  deployments/container/Dockerfile
  deployments/helm/dra-example-driver/templates/controller.yaml
  deployments/helm/dra-example-driver/templates/deviceclass.yaml
  deployments/helm/dra-example-driver/templates/resourceclass.yaml
  go.mod
  go.sum
  pkg/example.com/resource/clientset/versioned/clientset.go
  pkg/example.com/resource/clientset/versioned/fake/clientset_generated.go
  pkg/example.com/resource/clientset/versioned/fake/doc.go
  pkg/example.com/resource/clientset/versioned/fake/register.go
  pkg/example.com/resource/clientset/versioned/scheme/doc.go
  pkg/example.com/resource/clientset/versioned/scheme/register.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/deviceclassparameters.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/doc.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/doc.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/fake_deviceclassparameters.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/fake_gpu_client.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/fake/fake_gpuclaimparameters.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/generated_expansion.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/gpu_client.go
  pkg/example.com/resource/clientset/versioned/typed/gpu/v1alpha1/gpuclaimparameters.go
  pkg/flags/crds.go
  pkg/flags/kubeclient.go
Labels: lgtm, size/XXL, approved, cncf-cla: yes

#52 Update CDI specification to v0.8.0
  cmd/dra-example-kubeletplugin/cdi.go
  demo/scripts/kind-cluster-config.yaml
  go.mod
  go.sum
Labels: lgtm, size/M, approved, cncf-cla: yes

#53 Update to kubernetes v1.31.0
  README.md
  demo/scripts/common.sh
  go.mod
  go.sum
Labels: lgtm, size/M, approved, cncf-cla: yes

#51 Add support for Podman
  .gitignore
  Makefile
  README.md
  demo/build-driver.sh
  demo/create-cluster.sh
  demo/scripts/build-driver-image.sh
  demo/scripts/build-kind-image.sh
  demo/scripts/common.sh
  demo/scripts/create-kind-cluster.sh
  demo/scripts/delete-kind-cluster.sh
  demo/scripts/load-driver-image-into-kind.sh
  deployments/container/Makefile
Labels: lgtm, size/M, approved, cncf-cla: yes

#55 moq was using golang 1.23 for latest
  common.mk
  docker/Dockerfile.devel
Labels: lgtm, approved, size/XS, cncf-cla: yes

#54 Add support for opaque configs with examples
  README.md
  api/example.com/resource/gpu/v1alpha1/api.go
  api/example.com/resource/gpu/v1alpha1/deviceclass.go
  api/example.com/resource/gpu/v1alpha1/gpuclaim.go
  api/example.com/resource/gpu/v1alpha1/register.go
  api/example.com/resource/gpu/v1alpha1/sharing.go
  api/example.com/resource/gpu/v1alpha1/validate.go
  api/example.com/resource/gpu/v1alpha1/zz_generated.deepcopy.go
  cmd/dra-example-kubeletplugin/cdi.go
  cmd/dra-example-kubeletplugin/state.go
  demo/demo-apps.png
  demo/gpu-test1.yaml
  demo/gpu-test2.yaml
  demo/gpu-test3.yaml
  demo/gpu-test4.yaml
  demo/gpu-test5.yaml
  deployments/helm/dra-example-driver/crds/gpu.resource.example.com_deviceclassparameters.yaml
  deployments/helm/dra-example-driver/crds/gpu.resource.example.com_gpuclaimparameters.yaml
Labels: lgtm, size/XXL, approved, cncf-cla: yes
