Repository kubernetes-sigs/dra-example-driver, pull requests merged in 2025-08, with the labels that each got.

#111 Make number of simulated devices configurable via Helm
  deployments/helm/dra-example-driver/templates/kubeletplugin.yaml
  deployments/helm/dra-example-driver/values.yaml
  test/e2e/setup-e2e.sh
Labels: lgtm, ok-to-test, approved, size/XS, cncf-cla: yes

#116 Updated DRA APIs to v1
  README.md
  cmd/dra-example-kubeletplugin/discovery.go
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  cmd/dra-example-kubeletplugin/state.go
  demo/gpu-test1.yaml
  demo/gpu-test2.yaml
  demo/gpu-test3.yaml
  demo/gpu-test4.yaml
  demo/gpu-test5.yaml
  demo/gpu-test6.yaml
  demo/scripts/common.sh
  demo/scripts/kind-cluster-config.yaml
  go.mod
  go.sum
  test/e2e/e2e.sh
Labels: size/XL, lgtm, approved, cncf-cla: yes

#120 Cut v0.2.0
  common.mk
  deployments/helm/dra-example-driver/Chart.yaml
Labels: lgtm, approved, size/XS, cncf-cla: yes
