Repository kubernetes-sigs/dra-example-driver, pull requests merged in 2025-05, with the labels that each got.

#95 Bump k8s.io dependencies to 1.33
  .github/workflows/e2e.yaml
  .github/workflows/tests.yaml
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  common.mk
  demo/scripts/common.sh
  deployments/helm/dra-example-driver/Chart.yaml
  go.mod
  go.sum
  pkg/flags/logging.go
Labels: lgtm, size/L, approved, cncf-cla: yes

#99 add Jon Huhn to OWNERS
  OWNERS
Labels: lgtm, approved, size/XS, cncf-cla: yes

#98 Make kubelet plugin dirs configurable
  cmd/dra-example-kubeletplugin/driver.go
  cmd/dra-example-kubeletplugin/main.go
  cmd/dra-example-kubeletplugin/state.go
  deployments/helm/dra-example-driver/templates/kubeletplugin.yaml
  deployments/helm/dra-example-driver/values.yaml
Labels: lgtm, size/M, approved, cncf-cla: yes

#87 Update RELEASE.md
  RELEASE.md
Labels: lgtm, size/M, approved, cncf-cla: yes
